springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  application:
    name: AI-Resume-Evaluator

  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-4o
          temperature: 0.2
          max_tokens: 1000